## all relative paths in this file has pybullet_planning as the root dir

## debug related
seed: null
verbose: true

## configuration for PDDLStream
planner:
  visualization: false
  domain_pddl: 'pddl_domains/pr2_domain_pigi.pddl'
  stream_pddl: 'pddl_domains/pr2_stream_pigi.pddl'
  scene_only: false
  use_heuristic_fc: false
  dataset_mode: true
  downward_time: 10
  evaluation_time: 30
  stream_planning_timeout: 60
  total_planning_timeout: 360
  max_plans: 25
  max_solutions: 1
  log_failures: false

world:
  ## method 1: use pre-specified builder inside world_builder/builders,
  ##         followed by builder specific arguments
  builder_name: 'test_kitchen_full'
  builder_kwargs:
    movable_categories: ['edible']
    goal_predicates: ['openedjoint', 'holding', 'on', 'in']

## specify the TAMP problem with preconfigured scene layout & robot
problem:
  problem: 'test_full_kitchen'
  goal_variations: [21]
  domain_pddl: 'pddl_domains/pr2_domain_pigi.pddl'
  stream_pddl: 'pddl_domains/pr2_stream_pigi.pddl'
  use_skeleton_constraints: false
  use_subgoal_constraints: false
  use_all_grasps: false
  use_rel_pose: false
  preview_plan: false
  preview_scene: false

## outputs to generate
data:
  out_dir: '../outputs/custom_pr2_kitchen_full_pigi/'
  exp_dir: '../outputs'
  exp_subdir: 'custom_piginet_data'
  exp_name: 'original'
  record_problem: true
  record_mp4: false
  save_testcase: false

robot:
  robot_name: 'pr2'
  draw_base_limits: true

## planning stream related
streams:
  debug: false
  cfree: false
  teleport: false
  disable_movable_collision: false
  disable_base_collision: false
  top_grasp_tolerance: 0.8
  ir_max_attempts: 15
  use_all_grasps: false

## pybullet related
sim:
  window_width: 720
  window_height: 619
  viewer: true
  lock: true
  simulate: false
  drive: false
  cfree: false
  time_step: 0.05
  camera: false
  segment: false
  monitoring: false
  show_object_names: true